### ISSUE TITLE
Repmat

### ISSUE THREAD

**Issue by rifqifatih** [infrontoftheforest/TDCV#1]
```
repmat(orig', size(vert1, 1), 1),... %from the func docs
repmat(ray',  size(vert1, 1), 1),...
```

I think TriangleRayIntersecation.m already done the `repmat(A, size(B,1), 1)` for you if you have different size? For me just putting orig, ray works fine.

**Comment by infrontoftheforest** [comment]
Yes, I think you are right. I'll change it.
