### ISSUE TITLE
Implement RANSAC

### ISSUE THREAD

**Issue by infrontoftheforest** [infrontoftheforest/TDCV#2]
For part 2, I have created a first attempt at RANSAC, but it isn't working. Let's take a look at it together.

**Comment by rifqifatih** [comment]
Thinking of either tuning:
- SIFT features from task 1
- `threshold_ubcmatch`
- N iteration

**Comment by rifqifatih** [comment]
Tune our ray in task 1 to something shorter (not with length 1) in order to get more SIFT keypoints. Though I don't know the ideal lambda for each ray.

**Comment by infrontoftheforest** [comment]
I just figured it out. Change ray to 
`ray = Q\m;`
The origin is already taken into account for the intersection function. Maybe it should be called `dir` instead.

**Comment by rifqifatih** [comment]
@infrontoftheforest I guess I need to read the docs more thoroughly.....
